Program8D :    program88d.o funkcje8.o
	gcc -o Program8D program88d.o funkcje8.o -Wall -pedantic -std=c11 -lm
funkcje8.0:	funkcje8.c
	gcc -o funkcje8.o -c funkcje8.c -Wall -pedantic -std=c11
program8d.o:	program88d.c
	gcc -o program88d.o -c program88d.c -Wall -pedantic -std=c11
