# Tomasz Nalecz
# Grupa U2
# 29.05.2020r.
program: main.o funkcje.o
	gcc -o program main.o funkcje.o -Wall -pedantic -std=c11 -lm
funkcje.o:	funkcje.c
		gcc -o funkcje.o -c funkcje.c -Wall -pedantic -std=c11
main.o:	main.c
	gcc -o main.o -c main.c -Wall -pedantic -std=c11		
