Program7D :    program7d.o funkcje7.o
	gcc -o Program7D program7d.o funkcje7.o -Wall -pedantic -std=c11 -lm
funkcje7.0:	funkcje7.c
	gcc -o funkcje7.o -c funkcje7.c -Wall -pedantic -std=c11
program7d.o:	program7d.c
	gcc -o program7d.o -c program7d.c -Wall -pedantic -std=c11
